plugins {
    id 'com.enonic.xp.app'
    id 'com.enonic.defaults' version '2.1.6'
    id 'maven-publish'
}

dependencies {
    implementation xplibs.api.script
    include xplibs.content
    include xplibs.portal
    include xplibs.context
    include xplibs.export
    include xplibs.project
    include xplibs.cluster

    include libs.lib.mustache
    include libs.lib.thymeleaf
    include libs.lib.asset
}

repositories {
    mavenCentral()
    xp.enonicRepo('dev')
}
